//接口集合
let httpUrl = {
  /* account */
  // 获取用户关注列表
  "getAttention": "/api/user/attention",
  // 获取/更新 用户基本信息
  "getUser": "/api/user",
  // 获取他人用户基本信息
  "getOtherUser": "/api/user/",
  // 用户详细信息
  "userDetailedInfo": "/api/user/userDetailedInfo",
  // 获取图片上传凭证
  "imageCredentials": "/api/images/credentials/",
  // 补全image信息
  "matchingImage": "/api/images/matching",
  // 更新用户封面
  "updatacover": "/api/user/cover/",
  // 更新用户头像
  "updataheadImage": "/api/user/headImage/",
  // 获取文章列表
  "articleList": "/article",
  // 获取用户收藏的文章列表
  "collectionArticle": "/api/article/collect",
  // 获取用户收藏的悬赏列表
  "collectionReward": "/api/rewardDemand/collect",
  // 提交悬赏
  "postRewardDemand": "/api/rewardDemand",
  // 获取悬赏列表
  "rewardList": "/rewardDemand",
  // 获取用户关注列表
  "attentionList": "/api/user/attention",
  // 用户消息数量信息
  "userMsgNum": "/api/user/msgNum",
  // 阅读直接推送来的消息（前）
  "messageWatch_": "/api/message/",
  // 阅读直接推送来的消息（后）
  "_messageWatch": "/watch",
  // 获取用户粉丝列表
  "followList": "/api/user/follow",
  // 关注用户
  "postFollow": "/api/user/follow/",
  // 取消关注用户
  "postUnFollow": "/api/user/unFollow/",
  // 取消关注用户
  "postUnFollow": "/api/user/unFollow/",
  // 获取聊天关系记录
  "chatRelation": "/api/message/chatRelation",
  // 用户自己的爱好列表
  "userHobbies": "/api/user/hobbies",
  // 获取草稿列表
  "articleDraftList": "/api/article/articleDraft",
  // 根据获取聊天关系获取消息（前）
  "messageId_": "/api/message/",
  // 根据获取聊天关系获取消息（后）
  "_chatRelation": "/chatRelation",
  // 关注爱好
  "hobbyAdd": "/api/hobby/add/",
  // 取消关注爱好
  "hobbyReduce": "/api/hobby/reduce/",
  // 保存文章草稿
  "articleDraft": "/api/article/articleDraft",
  // 发布文章草稿为正式
  "articlePublish": "/api/article/publish/",
  // 阅读文章
  "articleWatch": "/api/article/watch/",
  // 查看当前文章当前用户是否收藏和点赞
  "article": "/api/article/",
  // 更新文章封面（后）
  "_cover": "/cover",
  // 收藏文章
  "articleGiveCollect": "/api/article/giveCollect/",
  // 取消收藏
  "articleReduceCollect": "/api/article/reduceCollect/",
  // 点赞文章
  "articleGiveStar": "/api/article/giveStar/",
  // 取消点赞
  "articleReduceStar": "/api/article/reduceStar/",
  // 创建一级评论
  "createComment": "/api/comment",
  // 创建二级评论
  "createCommentSub": "/api/comment/sub",
  // 删除一级评论
  "delComment": "/api/comment/",
  // 删除二级评论
  "delCommentSub": "/api/comment/sub/",
  // 点赞二级评论
  "starCommentSub": "/api/comment/sub/star/",
  // 取消点赞二级评论
  "unStarCommentSub": "/api/comment/sub/unStar/",
  // 创建@记录
  "createCommentRemind": "/api/comment/remind",
  // 点赞评论
  "commentStar": "/api/comment/star/",
  // 取消点赞评论
  "commentUnStar": "/api/comment/unStar/",
  // 阅读评论评论
  "commentWatch": "/api/comment/watch/",
  // 子评论分页列表
  "commentSub": "/comment/sub",
  // 保存文章
  "saveArticle": "/api/article",
  // 文章前缀(前)
  "article_": "/api/article/",
  // 文章修改积分(后)
  "_integral": "/integral",
  // 购买文章(后)
  "_buy": "/buy",
  // 系统消息列表
  "messageSystem": "/api/message/system",
  // 阅读系统消息(前)
  "messageSystem_": "/api/message/system/",
  // 更新微信小程序用户手机号
  "phoneWxMini": "/api/user/phone/wxMini",
  // 获取文章草稿详情
  "articleDraftId": "/api/article/articleDraft/",
  // 撤销(后)
  "_revoke": "/revoke",
  // 修改用户手机性能参数
  "performance": "/api/user/performance/",
  // 举报
  "report": "/feedBack/report",
  // 悬赏前缀(前)
  "rewardDemand_": "/api/rewardDemand/",
  // 收藏悬赏
  "giveCollectId": "/api/rewardDemand/giveCollect/",
  // 取消收藏悬赏
  "reduceCollectId": "/api/rewardDemand/reduceCollect/",
  // 点赞悬赏
  "giveStarId": "/api/rewardDemand/giveStar/",
  // 取消点赞悬赏
  "reduceStarId": "/api/rewardDemand/reduceStar/",
  // 延时悬赏(后)
  "_extension": "/extension",
  // 增加悬赏金(后)
  "_addReward": "/addReward",
  // 返还积分
  "applyCancel": "/api/rewardDemand/applyCancel",
  // 悬赏补充内容
  "rewardDemandAddText": "/api/rewardDemand/addText",
  // 文章补充内容
  "articleAddText": "/api/article/addText",
  // 收藏坐标 & 已收藏列表
  "coordinate": "/api/celestialBody/coordinate",
  // 修改坐标点名称
  "coordinateName": "/api/celestialBody/coordinate/name",
  // 提交悬赏内容
  "rewardDemandResult": "/api/rewardDemand/result",
  // 悬赏选定回答
  "rewardDemandSelectId": "/api/rewardDemand/selected/",
  // 给选定的悬赏回答评分
  "rewardDemandEvaluate": "/api/rewardDemand/evaluate",
  // 回答相关（前）
  "rewardSubmission_": "/api/rewardDemand/rewardSubmission/",
  // 提现订单
  "ordersWithdrawal": "/api/orders/withdrawal",
  // 充值
  "recharge": "/api/user/recharge",
  // 提现
  "withdrawal": "/api/user/withdrawal",
  // 阅读悬赏
  "rewardDemandWatch": "/api/rewardDemand/watch/",
  // 订单分页
  "orders": "/api/orders",
  // 已购列表
  "purchased": "/api/orders/purchased",
  // 维持登陆
  "health": "/actuator/health",
  // 修改收藏坐标名称
  "coordinateName": "/api/celestialBody/coordinate/name",
  // 悬赏回答草稿列表
  "rewardSubmissionDraft": "/api/rewardDemand/rewardSubmission/draft",
  // 悬赏回答草稿相关接口
  "rewardSubmissionDraft_": "/api/rewardDemand/rewardSubmission/draft/",
  // publish 后缀
  "_publish": "/publish",
  // user 后缀
  "_user": "/user",


  /* app */
  // 获取文章列表
  "appArticle": "/article",
  // 获取文章详情
  "appArticleInfo": "/article/",
  // 获取他人用户信息
  "getOtherUser": "/user/",
  // 申请爱好
  "hobbyApply": "/feedBack/hobbyApply",
  // 获取星球信息
  "getCelestialBody_all": "/celestialBody",
  // 获取星球信息
  "getCelestialBody": "/celestialBody/",
  // 获取星域内的数据
  "getCelestialBodyStarDomain": "/celestialBody/starDomain/",
  // 获取一级评论分页
  "comment": "/comment",
  // 搜索爱好
  "hobbySearch": "/hobby/search",
  // 获取悬赏详情
  "rewardDemandId": "/rewardDemand/",
  // 悬赏回答列表
  "_rewardSubmission": "/rewardSubmission",
  // 获取合并后图片
  "celestialBody_": "/celestialBody/",
  "_image": "/image",
};

export default {
  httpUrl: httpUrl
}